version: "3.7"
services:

  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    ports:
      - "9696:9696"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - /home/thor/.config/prowlarr>:/config

  overseerr:
    container_name: overseerr
    image: ghcr.io/hotio/overseerr
    ports:
      - "5055:5055"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Vancouver
    volumes:
      - /home/thor/.config/overseerr:/config
      - /gmedia:/data/media

  sabnzbd:
    container_name: sabnzbd
    image: ghcr.io/hotio/sabnzbd:testing
    ports:
      - "6789:8080"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Vancouver
    volumes:
      - /home/thor/.config/sabnzbd:/config
      - /downloads:/data/downloads
    restart: unless-stopped

  bazarr:
    container_name: bazarr
    image: cr.hotio.dev/hotio/bazarr:nightly
    ports:
      - "6767:6767"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Vancouver
    volumes:
      - /home/thor/.config/bazarr:/config
      - /data:/data
    restart: unless-stopped

  sonarr:
    container_name: sonarr
    image: cr.hotio.dev/hotio/sonarr:v4
    ports:
      - "8989:8989"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Vancouver
    volumes:
      - /home/thor/.config/sonarr:/config
      - /data:/data
    restart: unless-stopped

  radarr:
    container_name: radarr
    image: cr.hotio.dev/hotio/radarr:nightly
    ports:
      - "7878:7878"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Vancouver
    volumes:
      - /home/thor/.config/radarr:/config
      - /data:/data
    restart: unless-stopped

  # plex:
  #   image: lscr.io/linuxserver/plex:latest
  #   container_name: plex
  #   network_mode: host
  #   environment:
  #     - VERSION=latest
  #     - PGID=1000
  #     - PUID=1000
  #     - PLEX_UID=1000
  #     - PLEX_GID=1000
  #     - PLEX_CLAIM="claim-Ei2rVbLtux__fcaugf2j"
  #     - TZ=America/Vancouver
  #   volumes:
  #     - /gmedia:/data/media
  #     - /cache/plex/transcodes:/transcode
  #     - /mnt/plex-meta:/config
  #   restart: always
  #   devices:
  #     - '/dev/dri:/dev/dri'

  tautulli:
      image: lscr.io/linuxserver/tautulli:latest
      container_name: tautulli
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=America/Vancouver
      volumes:
        - /home/thor/.config/tatulli:/config
      ports:
        - 8181:8181
      restart: unless-stopped

  