version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PGID=129
      - PUID=1000
      - PLEX_UID=1000
      - PLEX_GID=129
      - PLEX_CLAIM="claim-Ei2rVbLtux__fcaugf2j"
      - TZ=America/Vancouver
    volumes:
      - /gmedia:/data/media
      - /cache/plex/transcodes:/transcode
      - /home/thor/.config/plex:/config
    restart: unless-stopped
    devices:
      - '/dev/dri:/dev/dri'