version: "2.1"
services:
  sabnzbd:
    container_name: sabnzbd
    image: ghcr.io/hotio/sabnzbd:testing
    ports:
      - "8080:8080"
    environment:
      - PUID=1000
      - PGID=129
      - UMASK=002
      - TZ=America/Vancouver
    volumes:
      - /home/thor/.config/sabnzbd:/config
      - /downloads:/data/downloads
    restart: unless-stopped

  bazarr:
    container_name: bazarr
    image: cr.hotio.dev/hotio/bazarr:nightly
    ports:
      - "6767:6767"
    environment:
      - PUID=1000
      - PGID=129
      - UMASK=002
      - TZ=America/Vancouver
    volumes:
      - /home/thor/.config/bazarr:/config
      - /gmedia:/data/media
    restart: unless-stopped

  sonarr:
    container_name: sonarr
    image: cr.hotio.dev/hotio/sonarr:v4
    ports:
      - "8989:8989"
    environment:
      - PUID=1000
      - PGID=129
      - UMASK=002
      - TZ=America/Vancouver
    volumes:
      - /home/thor/.config/sonarr:/config
      - /downloads:/data/downloads
      - /gmedia:/data/media
    restart: unless-stopped

  radarr:
    container_name: radarr
    image: cr.hotio.dev/hotio/radarr:nightly
    ports:
      - "7878:7878"
    environment:
      - PUID=1000
      - PGID=129
      - UMASK=002
      - TZ=America/Vancouver
    volumes:
      - /home/thor/.config/radarr:/config
      - /gmedia:/data/media
      - /downloads:/data/downloads
    restart: unless-stopped

  # plex:
  #   image: lscr.io/linuxserver/plex:latest
  #   container_name: plex
  #   network_mode: host
  #   environment:
  #     - VERSION=latest
  #     - PGID=129
  #     - PUID=1000
  #     - PLEX_UID=1000
  #     - PLEX_GID=129
  #     - PLEX_CLAIM="claim-Ei2rVbLtux__fcaugf2j"
  #     - TZ=America/Vancouver
  #   volumes:
  #     - /gmedia:/data/media
  #     - /cache/plex/transcodes:/transcode
  #     - /mnt/plex-meta:/config
  #   restart: always
  #   devices:
  #     - '/dev/dri:/dev/dri'

  tautulli:
      image: lscr.io/linuxserver/tautulli:latest
      container_name: tautulli
      environment:
        - PUID=1000
        - PGID=129
        - TZ=America/Vancouver
      volumes:
        - /home/thor/.config/tatulli:/config
      ports:
        - 8181:8181
      restart: unless-stopped

  # grafana:
  #   container_name: grafana
  #   volumes:
  #     - /home/thor/.config/grafana:/var/lib/grafana
  #   logging:
  #     driver: loki
  #     options:
  #         loki-url: http://192.168.1.172:3100/loki/api/v1/push
  #   ports:
  #       - '3000:3000'
  #   image: grafana/grafana
  #   depends_on: 
  #     - loki
  #     - promtail
    
  # loki:
  #   container_name: loki
  #   ports:
  #       - '3100:3100'
  #   image: grafana/loki

  # promtail:
  #   image: grafana/promtail:2.6.1
  #   volumes:
  #     - /var/log:/var/log
  #   command: -config.file=/etc/promtail/config.yml

  
  # elasticsearch:
  #   container_name: elasticsearch
  #   hostname: elasticsearch
  #   image: "docker.elastic.co/elasticsearch/elasticsearch:8.5.2"
  #   logging:
  #     options:
  #       max-file: "3"
  #       max-size: "50m"
  #   environment:
  #     - http.host=0.0.0.0
  #     - transport.host=127.0.0.1
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms${ES_JVM_HEAP} -Xmx${ES_JVM_HEAP}"
  #   mem_limit: 1g
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - /home/thor/.config/elasticsearch:/usr/share/elasticsearch/config
  #     - /home/thor/.config/elasticsearch/data:/usr/share/elasticsearch/data
  #   ports: 
  #     - '9200:9200'
