version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - VERSION=docker
      - PGID=129
      - PUID=1000
      - PLEX_UID=1000
      - PLEX_GID=129
      - PLEX_CLAIM="claim-Ei2rVbLtux__fcaugf2j"
      - TZ=America/Vancouver
    volumes:
      - /gmedia:/data/media
      - /cache/plex/transcodes:/transcode
      - /home/thor/.config/plex:/config
    restart: unless-stopped
    devices:
      - '/dev/dri:/dev/dri'

  grafana:
    container_name: grafana
    ports:
        - '3000:3000'
    image: grafana/grafana
    
  loki:
    container_name: loki
    ports:
        - '3100:3100'
    image: grafana/loki
  
  elasticsearch:
    container_name: elasticsearch
    hostname: elasticsearch
    image: "docker.elastic.co/elasticsearch/elasticsearch:latest"
    logging:
      options:
        max-file: "3"
        max-size: "50m"
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms${ES_JVM_HEAP} -Xmx${ES_JVM_HEAP}"
    mem_limit: 1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /home/thor/.config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /home/thor/.config/elasticsearch/data:/usr/share/elasticsearch/data
    ports: 
      - '9200:9200'